# Generated by Django 4.1 on 2024-09-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("portfolioName", models.CharField(max_length=50)),
                ("initialInvestmentAmount", models.BigIntegerField(default=0)),
                ("riskToleranceLevel", models.CharField(max_length=50)),
                ("investmentStrategy", models.CharField(max_length=250)),
                ("rid", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "sos_portfoliomanagement",
            },
        ),
    ]
